name: CERTAIN
channels:
  - conda-forge
  - defaults
  - plotly
dependencies:
  - python=3.11
  - pytest=8.4.1
  - ydata-profiling=4.12.1
  - plotly=5.24.1
  - plotly-orca=1.3.1
  - psutil=7.0.0
  - pip:
      - fpdf2=2.8.2